create remitano payment extension
remitano/remitano-opencart pull request #1
Opened 2021-07-26 09:44 UTC by tannguyen

2021-07-27 03:35 UTC, khoinguyenm commented on catalog/view/theme/default/template/extension/payment/paypal_standard.twig
> +{% if testmode %}
file dư

2021-07-27 03:44 UTC, khoinguyenm commented
@tannguyen  a có 1 số chỗ góp ý về code style:
- Add dư mấy file .ds_store, nên thêm .gitignore để handle vụ này
- Identation chưa thống nhất, file thì 2 space file thì 4 space file thì tab. 
- Mỗi thằng nó sẽ có 1 convention riêng mình cần follow nếu muốn publish library lên store, ví dụ opencart thì tham khảo: https://github.com/opencart/opencart/wiki/Coding-standards, theo cái này thì cần sử dụng tab indentation và tên function phải là camelCase

2021-07-27 04:00 UTC, khoinguyenm requested changes

2021-07-27 04:00 UTC, khoinguyenm commented on admin/controller/extension/payment/remitano.php
> +    //Create index method. Index method is called automatically if no parameters are passed, check this video tutorial for details https://www.youtube.com/watch?v=X6bsMmReT-4.
vì library này sẽ public open source nên anh nghĩ nên bỏ bớt mấy comment này

2021-07-27 04:00 UTC, khoinguyenm commented on catalog/controller/extension/payment/remitano.php
> +<?php
file này với file admin/controller/extensionn/payment/remitano.php có nội dung giống nhau, vậy mình cần xài file nào mới đúng?

2021-07-27 04:00 UTC, khoinguyenm commented on catalog/model/extension/payment/remitano.php
> +			curl_setopt($curl, CURLOPT_URL, 'https://api.remitano.com/api/v1/merchant/merchant_charges');
chỗ này nếu dc nên tìm cách refactor lại cho nó DRY

2021-07-27 05:15 UTC, tannguyen commented on catalog/controller/extension/payment/remitano.php
> +<?php
Úi em hqua mới push code wip lên,  chắc em lỡ tay assign anh @khoinguyenm chứ pull này chưa ready to review ạ 😅

2021-07-28 09:09 UTC, tannguyen commented
anh @khoinguyenm review dùm em nha

2021-07-28 09:19 UTC, khoinguyenm requested changes
e cho thêm screenshot của admin setting và trang checkout nha

2021-07-28 09:19 UTC, khoinguyenm commented on admin/language/en-gb/extension/payment/remitano.php
> +$_['text_success'] = 'Success: You have modified remitano key details!';
viết hoa Remitano

2021-07-28 09:19 UTC, khoinguyenm commented on admin/language/en-gb/extension/payment/remitano.php
> +$_['text_remitano'] = '<a target="_BLANK" href="https://remitano.com/payment_gateway"><img src="view/image/payment/remitano.png" alt="Remitano payment gateway" title="Remitano payment gateway" style=
Viết hóa Payment Gateway

2021-07-28 09:19 UTC, khoinguyenm commented on catalog/language/en-gb/extension/payment/remitano.php
> +$_['text_title']	= 'Remitano payment gateway';
Viết hoa

2021-07-28 09:19 UTC, khoinguyenm commented on install.xml
> +            test123
file này có ý nghĩa gì nhỉ?

2021-07-28 09:30 UTC, tannguyen commented on install.xml
> +            test123
có file này thì mới cài được extension  qua Opencart Modification System trên giao diện admin ạ https://webkul.com/blog/opencart-modification-system/

2021-07-28 09:34 UTC, tannguyen commented
@khoinguyenm  em đã thêm screenshot trang admin và checkout ạ

2021-07-28 09:36 UTC, khoinguyenm commented on install.xml
> +            test123
@tannguyen nếu vậy sao giá trị của mình ở đây là test123 nhỉ?

2021-07-28 09:43 UTC, tannguyen commented on install.xml
> +            test123
@khoinguyenm dạ em xóa đi rồi nha

2021-07-28 09:44 UTC, tannguyen commented on install.xml
> +            test123
file này vẫn cần thêm link hướng dẫn setup trên api doc của mình nữa, mà em chưa tạo pull cho việc đó nên cũng chưa có link, em sẽ thêm sau

2021-07-29 01:34 UTC, khoinguyenm approved these changes

2021-07-29 02:55 UTC, merged

2021-07-29 08:42 UTC, tannguyen commented
pr này em thấy nút merge nó xanh, em bấm thử thì nó merge được thật, sorry anh em @tannauit @linhlymanh 🙏